#################################
# Development
#################################
FROM node:13-alpine as build-stage

WORKDIR /app

COPY package*.json ./

# Install app dependencies
RUN npm install -g @angular/cli
RUN npm set progress=false
RUN npm install

# Copy all files to app folder
COPY . .

# Add configuration files
COPY image-files/ /

# Install nginx
RUN apk --update add nginx

# Expose port 80
EXPOSE 80

ENTRYPOINT ["docker-entrypoint-dev.sh"]
